name: neuraluserbaselines
channels:
  - defaults
  - conda-forge
  - pytorch
  # - fastai
dependencies:
  - python>=3.7, <3.9
  - pip
  # BASICS
  - click
  - pip:
     - "git+https://github.com/thu-coai/ConvLab-2.git@a83b8f108dce3f0f7bb801c7abe403423436458f#egg=Convlab-2"
     - omegaconf>=2.1.0, <3.0.0
