name: crazyneuraluser
channels:
  - defaults
  - conda-forge
  - pytorch
  # - fastai
dependencies:
  - python>=3.8, <3.9
  - pip

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
#  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
#  - nbstripout
  - sphinx
  - recommonmark
