name: crazyneuraluser
channels:
  - defaults
  - conda-forge
  - pytorch
  # - fastai
dependencies:
  - python>=3.7, <3.8
  - pip
  # BASICS
  - click
  - pip:
     - -e .  # install git checkout of crazyneuraluser in editable mode
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     # - icecream
     # - jax
     # - numpyro
     # - funsor
     # - neptune-client
     # - neptune-contrib
