model:
  path: "./models/user_model/MultiWOZ-full_checkpoint_step340k"
  goal_update:
    finish_inform: "loose" # loose or strict

schema_path: "scripts/user_model_code/interaction/schema.json"

decode:
  dec_max_len: 1024
  num_beams: 1
  temperature: 0.7
  do_sample: False
